title: "Digital Phoenix Dev Blog"
description: "Updates and behind-the-scenes progress from our team."
theme: none
markdown: kramdown

# Custom domain setup
url: "https://digitalphxgames.com"
baseurl: ""